---
title: "To Explain or to Predict?"
subtitle: "Discussion of research paper by Galit Shmueli"
format:
    revealjs:
        slide-number: true
        preview-links: true
        theme: default
---
# Introduction

## About Galit Shmueli

- 46 y/o, Dr. Galit Shmueli is a Chair Professor at the National Tsing Hua University in Taiwan.
- Authored many influential works in predictive analytics, data mining, and business analytics.
- "To Explain or to Predict?" is Shmueli's most cited work, 3,679 times.

## Purpose of To Explain or to Predict

- Tackling the distinction between explanatory and predictive modelling in Statistics.
- Lack of this distinction creates multiple problems within different disciplines.
  - Gap between academia and practice
  - Finance, psychology, philosophy

# Background

## Explanatory Modeling
- Explaining: Causal explanation
- Explanatory modeling: Use of statistical models for testing causal explanations
- In practice: association-based models are applied to observational data
  - Most common: Regression model
  - Justification: Theory itself provides the causality 

## Predictive Modeling
- Predictive Modeling: the process of applying a statistical model or data mining algorithm to data for the purpose of predicting new or future observations.
- Shmueli focuses on "nonstochastic prediction" - the goal being to predict output value for new observations given their input values.

## Descriptive Modeling
- Descriptive Modeling: aimed at summarizing or representing the data structure in a compact manner
- Absent or less incorporated causal theory
- Regression:
  - Can be descriptive if used for capturing the association between dependent and independent variables
  - Not descriptive if purpose is causal inference or prediction

# Why they are different

## Cause
- Theory:
  - Suppose a theory that construct X causes construct Y via function F
  - Statistical model, f, defined as E(Y) = f(X)
- Explanatory modeling attempts to match f and F as closely as possible
- Predictive modeling attempts to utilize X, Y, and model f to generate good predictions of Y

## Effect - Causation Association
- Causation-Association:
  - Explanatory: Model f represents an underlying causal function, X is assumed to cause Y.
  - Predictive: Model f captures assocation between X and Y.

## Effect - Theory-Data
- Theory-Data:
  - Explanatory: Model f is constructed based on F in a way that supports the interpretation of the relationship between X, Y, and testing the causal hypotheses.
  - Predictive: Model f is constructed from the data. Interpretability of the relationship between X & Y are not required, sometimes desired for transparency.

## Effect - Retrospective-Prospective:
- Retrospective-Prospective:
  - Explanatory: Retrospective, model f is used to test an existing set of hypotheses.
  - Predictive: Prospective, model f is constructed for new observations.

## Effect - Bias-Variance:
  - Explanatory: Focus is on minimizing bias to obtain the most accurate representation of the theory.
  - Predictive: 
    - Focus is on minimizing bias and estimation variance. May occasionally sacrifice accuracy for empirical precision. 
    - "Wrong" model may predict better than the "correct" one.

# Statistical Modeling Differences

## Study Design and Data Collection
::: {.r-fit-text}
- Explanatory: 
  - Smaller n, just enough to reduce bias
  - Increase in number of groups in hierarchial data
  - Clean, experimental data
  - Valid, reliable data collection tool, accurately reflecting studied concepts
  - Factorial designs
- Prediction:
  - Larger n
  - Increase in size of group in hierarchial data
  - Observational data, avoiding "overly clean"
  - Measurement quality & meaning to the predicting variable
:::

## Data Preparation
::: {.r-fit-text}
- Explanatory:
  - Partitioning is less common, i.e. test sets, because of the reduction in statistical power.
    - When used, can be useful for model validity.
- Predictive:
  - Data partitioning has become a standard preprocessing step.
  - Missing values:
    - Depends on the relationship between the missingness and dependent variable.
      - In cases of financial fraud, missingness can be a blessing in disguise.
    - Estimate multiple reduced models, creating different models for different observations.
:::

## Exploratory Data Analysis
- Explanatory:
  - EDA is geared toward specified causal relationships.
  - Search for numerical summaries of the theoretical relationships.
- Predictive:
  - Capturing potentially unknown relationships.
  - Explore a large number of numerical summaries seeking unknown relationships.
  - Reduction in the number of variables reduces sampling variance.


## Choice of Variables
::: {.r-fit-text}
- Explanatory:
  - Goal is to understand causal relationships by using variables represented in the theoretical constructs
  - Variables may be chosen based on the role of the variables based on different fields.
  - Hard to avoid bias, solutions include 2SLS.
  - May only include "control" variables that take place before the causal variable
  - Must include main effects if interaction terms of those effects
- Predictive:
  - Predictors must be available at time of prediction
  - Quality of association, data quality, 
:::


## Choice of Methods
::: {.r-fit-text}
- Explanatory:
  - Requires interpretable statistical models, f, therefore regression is popular.
  - Not suited for algorithmic models such as KNN or neural networks.
- Predictive:
  - f is often unknown, so can include statistical models and data mining algorithms. 
  - Algorithmic models are very suitable for predictive and descriptive modeling.
  - Shrinkage & Ensemble methods from Bias-Variance.
:::

## Validation, Evaluation, Selection
- Explanatory:
  - Model validation & model fit
  - Explanatory power, strength of relationship.
  - Selected from highest explanatory power.
- Predictive:
  - Generalization, ability of fitted model to predict new data.
  - Predictive power, performance of fitted model on new data.
  - Variety of methods for predictive accuracy, AIC, BIC.

## Model Use and Reporting
- Explanatory:
  - Used to create statistical conclusions, testing causal hypotheses.
  - In practical use, dominated by statistical inference.
- Predictive:
  - Practically used for scientific predictive studies.
  - Emphasize data, association, bias-variance, prospects of the study.

# Real Examples

## Netflix Prize - Predictive Approach
- Large sample size, ensemble of methods, setting the stage for explanatory research.
- Explanatory context leads to completely different modeling path.
- Winning team combined skills within computer science and statistics.

## eBay Auction Research - Explanatory Approach
- Previous explanatory research based in game theory, used to test robustness of hypothesized effects across different variables.
- Omit number of bidders due to endogeneity, adding bias to the model.
- Predictive models use flexible, algorithmic models with low interpretability but high predictive accuracy.
- Cannot provide causal explanations, but shed light on new variables related to price. 

# Implications and Shmueli's Suggestions

## Implications of indiscrimination in research
- Statistical modeling is used almost exclusively for explanatory modeling, losing the ability to test the relevance of existing theories.
- Lack of understanding leads to incorrect statistical conclusions.
- Omission of predictive modeling in theory development leads to irrelevance in the practical context, and creates a barrier to scientific progress.

## Implications of indiscrimination within Statistics
- Void of predictive methodology has been taken up by ML and data mining, with the primary goals being computationally efficient algorithms and tackling bias-variance tradeoff.
- Complexity of models are task-dependent, a complex explanatory model might be "simple" in predictive purposes.

## Shmueli's Remarks and Suggestions
- Become more aware of how statistical models are used outside of statistics and to create or refine methods for purposes outside of statistics.
- Emphasize the differences between explanatory, predictive, and descriptive modeling as early as possible within statistics and research courses, and advocate for more refined use of the prefix "predict" in statistical modeling.
